---
title: "Untitled"
author: "Charles Leahan"
date: "11/11/2020"
output: word_document
---
```{r, warning = FALSE}
library(tidyverse)
library(ggplot2)
library(mdsr)
```

```{r}
#View on the data

class(mpg)
head(mpg[,1:6],3) 
head(mpg[,7:11],3)
```

# Basic Plots 

```{r}
#Scatter Plot
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) 
```

```{r}
#Adding more variables

ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, color = class))
```

```{r}
#Can assign the basic plot to a variable, then add on the layers 

g <- ggplot(data = mpg)
g + geom_point(mapping = aes(x = displ, y = hwy),
               color = "blue", shape = 15)
```

# Facet Wrapping

```{r}
#Wrap by class 

h <- ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy))
h + facet_wrap(~ class, nrow = 2)
```

```{r}
#Facets by two variables 

h + facet_grid(drv ~ cyl)
```

Note: 

Can facet by 

* columns -> facet_grid(. ~ drv) 
* rows -> facet_grid(drv ~ . ) 

# Geometric Objects 

```{r}
#Scatter plot with smoothing curve overlayed
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy)) +
  geom_smooth(mapping = aes(x = displ, y = hwy))
```









```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



